### ISSUE TITLE
Mod Config

### ISSUE THREAD

**Issue by Mohron** [mariot7/XL-Food-Mod#1]
Would it be possible for you to add a config for this mod?  I would like to be able to disable OreGen from XL foods so I can control it with a stand-alone OreGen mod. I'm sure there are other people who would benefit from a config file.

**Comment by mariot7** [comment]
I'm already working on a config file, it will be released next week.

**Comment by mariot7** [comment]
I now finally released a new update that adds a config file with option to disable world generation. Sorry that it took so long, but I was on vacation. Anyway thanks for suggesting this!
