### ISSUE TITLE
Have the same language key with vanilla

### ISSUE THREAD

**Issue by TartaricAcid** [mariot7/XL-Food-Mod#10]
## Problem
- Vanilla
`tile.grass.name=Grass Block`
- XL Food Mod
`tile.grass.name=Grass`

## How To Fix?
In this [class](https://github.com/mariot7/XL-Food-Mod/blob/1.12.2/src/main/java/mariot7/xlfoodmod/blocks/Grass.java#L23-L31), change `setUnlocalizedName(name);` to `setUnlocalizedName(Reference.MOD_ID + name);`

**Comment by mariot7** [comment]
Thanks for letting me know about this. Will fix it soon!

**Comment by mariot7** [comment]
Fixed in v1.7.1.
