### ISSUE TITLE
here is a ru_ru.lang for our server :3 for last 1.7.10 version

### ISSUE THREAD

**Issue by Pa4ok** [mariot7/XL-Food-Mod#11]
itemGroup.tabXLFoodMod=Едаааа
tile.rock_salt.name=Каменная соль
tile.xlfoodmodgrass.name=Трава
tile.vanilla_flower.name=Цветок ванили
tile.chocolate_cake.name=Шоколадный торт
tile.oreo_cake.name=Торт Oreo
tile.cheese_cake.name=Чизкейк
tile.nether_cake.name=Nether Cake
tile.strawberry_cake.name=Клубничный торт
tile.pumpkin_cake.name=Тыквенный пирог
tile.pizza.name=Пицца
tile.rice_plant.name=Росток риса
item.rice_seeds.name=Семена риса
item.rice.name=Рис
item.butter_rice.name=Рисовое масло 
item.fried_rice.name=Жареный рис
tile.pepper_plant.name=Куст перца
item.pepper_seeds.name=Семена перца
item.pepper.name=Перец
tile.corn_plant.name=Росток кукурузы
item.corn_seeds.name=Семена кукурузы
item.raw_corn.name=Сырая кукуруза
item.corn.name=Кукуруза
tile.cucumber_plant.name=Куст огурца 
item.cucumber_seeds.name=Семена огурца
item.cucumber.name=Огурец
tile.lettuce_plant.name=Куст салата
item.lettuce_seeds.name=Семена салата
item.lettuce.name=Салат
tile.onion_plant.name=Луковый саженец
item.onion.name=Лук
tile.tomato_plant.name=Куст помидор
item.tomato_seeds.name=Семена помидор
item.tomato.name=Помидор
tile.strawberry_plant.name=Куст клубники
item.strawberry_seeds.name=Семена клубники
item.strawberry.name=Клубника
item.salt.name=Соль
item.dough.name=Тесто
item.cooked_dough.name=Приготовленное тесто
item.crouton.name=Крутон
item.butter.name=Масло
item.cheese.name=Сыр
item.cheese_puff.name=Сырная слойка
item.chips.name=Чипсы
item.salty_chips.name=Соленые чипсы
item.spicy_chips.name=Острые чипсы
item.onion_rings.name=Луковые кольца
item.cheesy_bread.name=Сырный хлеб
item.potato_bread.name=Картофельный хлеб
item.corn_bread.name=Кукурузный хлеб
item.baguette.name=Багет
item.fried_egg.name=Жареное яйцо
item.pancake.name=Блинчик
item.waffle.name=Вафли
item.macaroni_and_cheese.name=Макароны с сыром
item.spaghetti.name=Спагетти
item.enchilada.name=Шаурма
item.lasagne.name=Лазанья
item.jambon_beurre.name=Сэндвич с маслом и ветчиной
item.flesh.name=Мяско
item.sausage.name=Колбаса
item.bacon.name=Бекон
item.beef_jerky.name=Вяленая говядина
item.ground_beef.name=Говяжий фарш
item.raw_chicken_wing.name=Сырое куриное крылышко
item.cooked_chicken_wing.name=Приготовленное куриное крылышко
item.spicy_chicken_wing.name=Пряное куриное крылышко
item.bucket_of_fried_chicken.name=Ведро жареной курочки
item.top_bun.name=Верхняя булочка
item.bottom_bun.name=Нижняя булочка
item.hamburger.name=Гамбургер
item.chickenburger.name=Чикенбургер
item.cheeseburger.name=Чизбургер
item.hot_dog.name=Хот-Дог
item.slice_of_pizza.name=Кусочек пиццы
item.tortilla.name=Тортилья
item.taco.name=Тако
item.burrito.name=Буррито
item.kebab.name=Кебаб
item.chicken_sandwich.name=Сэндвич с курицей
item.blt_sandwich.name=BLT Sandwich
item.icecream_sandwich.name=Сэндвич с мороженым
item.bowl.name=Миска
item.garden_salad.name=Летний салат
item.chicken_salad.name=Куриынй салат
item.caesar_salad.name=Цезарь
item.onion_salad.name=Луковый салат
item.taco_salad.name=Салат тако
item.cucumber_soup.name=Огуречный салат
item.tomato_soup.name=Борщь
item.vegetable_soup.name=Суп
item.chicken_soup.name=Куриный суп
item.beef_stew.name=Тушеная говядина
item.pumpkin_stew.name=Тушеная тыква
item.caramel_apple.name=Карамельное Яблоко
item.marshmallow.name=Зефир
item.roasted_marshmallow.name=Жареный зефир
item.oreo_cookie.name=печенье Oreo
item.twinkie.name=Твинки
item.brownie.name=Пирожное
item.chocolate.name=Шоколад
item.chocolate_icecream_ball.name=Шарик шоколадного мороженого
item.vanilla_icecream_ball.name=Шарик ванильного мороженого
item.strawberry_icecream_ball.name=Шарик кубличного мороженого
item.icecream_cone.name=Мороженое
item.chocolate_icecream.name=Шоколадное мороженое
item.vanilla_icecream.name=Ванильное мороженое
item.strawberry_icecream.name=Клубничное мороженое
item.crescent_roll.name=Рогалик
item.donut.name=Пончик
item.sugar_donut.name=Сахарный пончик
item.chocolate_donut.name=Шоколадный пончик
item.vanilla_donut.name=Ванильный пончик
item.paper_cup.name=Бумажный стаканчик
item.vanilla_cupcake.name=Ванильный кекс
item.chocolate_cupcake.name=Шоколадный кекс
item.oreo_cupcake.name=Oreo кекс
item.strawberry_cupcake.name=Клубничный кекс
item.pie_shell.name=Пирог
item.apple_pie.name=Яблочный пирог
item.golden_apple_pie.name=Золотой яблочный пирог
item.cheese_pie.name=Сырный пирог
item.chicken_pot_pie.name=Куриный пирог
item.chocolate_pie.name=Шоколадный пирог
item.bacon_pie.name=Пирог с беконом
item.fish_pie.name=Пирог с рыбой
item.strawberry_pie.name=Клубничный пирог
item.tomato_sauce.name=Томатный соус
item.hot_sauce.name=Острый соус
item.chocolate_syrup.name=Шоколадный сироп
item.vanilla_extract.name=Настойка ванили
item.vanilla_cream.name=Ванильный крум
item.empty_can.name=Пустая банка
item.speedy_energy_drink.name=Энергетик "FAST"
item.healthy_energy_drink.name=Энергетик "HEALTH"
item.stealthy_energy_drink.name=Энергетик "STEAL"
item.strong_energy_drink.name=Энергетик "STRONG"
item.deadly_energy_drink.name=Энергетик "DEATH"
item.super_energy_drink.name=Энергетик "SUPER"
item.glass_mug.name=Стеклянная кружка
item.beer.name=Пиво
item.coffee_cup.name=Кофейная чашка
item.coffee.name=Кофе
item.cappuccino.name=Капучино
xlfoodmod.config.title=XL Food Mod Config
xlfoodmod.general.worldgen=World Gen
xlfoodmod.general.worldgen.tooltip=World Generation Settings
xlfoodmod.general.worldgen.rockgen=Rock Salt Generation
xlfoodmod.general.worldgen.rockgen.tooltip=Disable the generation of Rock Salt
xlfoodmod.general.worldgen.grassgen=Grass Generation
xlfoodmod.general.worldgen.grassgen.tooltip=Disable the generation of Grass
xlfoodmod.general.worldgen.flowergen=Vanilla Flower Generation
xlfoodmod.general.worldgen.flowergen.tooltip=Disable the generation of Vanilla Flowers

**Comment by mariot7** [comment]
Will add this soon. Thanks!

**Comment by mariot7** [comment]
Added in v1.8.0!
