### ISSUE TITLE
Seeds not plantable on loamy, sandy, or silty farmland from biomes o plenty.

### ISSUE THREAD

**Issue by Trinsdar** [mariot7/XL-Food-Mod#12]
When Playing exoria, I tried to plant pepper seeds on loamy farmland but they would pop off after a little bit. it seems to work fine with vanilla farmland. I haven't tested other crops yet.

I am using minecraft 1.12.2, version 1.7.1 of xl food mod, and version 7.0.1.2346 of biomes o plenty.
I am using the exoria modpack version 1.3.0c.

Edit: after further testing it looks like no seeds from your mod work with any biomes o plenty farmland.

**Comment by mariot7** [comment]
Thanks for reporting this! I'm working on a fix, expect a new update later this month.

**Comment by mariot7** [comment]
Added in v1.8.0!
