### ISSUE TITLE
Mining salt with Mekanism

### ISSUE THREAD

**Issue by jgeekw** [mariot7/XL-Food-Mod#14]
I cannot seem to input the right mod ID or item name to mine salt using mekanism's digital miner. What is the Mod ID or the ID of rock salt?

**Comment by mariot7** [comment]
Hi, sorry for the late reply.

The mod id is xlfoodmod and the ID for the rock salt is xlfoodmod:rock_salt

Also, could you describe in more detail what you were trying to do as I'm not familiar with that mod?

Thanks!

**Comment by mariot7** [comment]
I'm closing this as it's related to Mekanism and not this mod.
