### ISSUE TITLE
Can't plant XL Food Mod crops on Rustic or Farming for Blockheads farmland

### ISSUE THREAD

**Issue by inkdear** [mariot7/XL-Food-Mod#17]
Seeds can't be planted on Rustic Fertilized Soil or any of the fertilized farmlands from Farming for Blockheads. Other modded crops have varying results on the same soils (planting and popping off or just planting successfully)

Edit: They also can't be planted on the bonemealed farmland from Better with Mods or the Fertilized Dirt from Random Things.

**Comment by mariot7** [comment]
Thanks for the report. I'll work on a fix.

**Comment by mariot7** [comment]
Fixed in v1.9.1.
