### ISSUE TITLE
Support right-click harvesting for vanilla and other modded crops.

### ISSUE THREAD

**Issue by AssB0ys** [mariot7/XL-Food-Mod#18]
I love how you can harvest and replant by right-clicking the items featured in this mod, but this doesn't work with the games default ones(wheat, beetroot etc). In a scope of a big premade modpack I would usually use tinkers tools for this, or other mod adds this functionality for all crops, even modded(enderio does this).

This would be nice to have if I don't have any other mods to do this(if I don't play a premade modpack but my own compilation, I don't usually include too many mods) and I thought why don't this mod support at least games defaults crops, although the support for other modded crops would be super convenient too, of course, configurable.

**Additional context**
Works flawlessly on xl-food-mod crops doesn't work on games default crops(wheats, carrots etc)

**Comment by mariot7** [comment]
Yeah, I can do that. Thanks for the suggestion!

**Comment by mariot7** [comment]
Added in v1.9.1.

**Comment by Real-Gecko** [comment]
Can you make this feature optional?
