### ISSUE TITLE
In canSustainBush change the check to instanceof BlockFarmland

### ISSUE THREAD

**Issue by Yamahari** [mariot7/XL-Food-Mod#19]
Hi,
in its current state your mod doesn't support custom farmland blocks, e.g. my mod adds a new farmland block that extends the vanilla one but your crops can't grow on it because you only check for the vanilla block

**Comment by mariot7** [comment]
I'm afraid that this isn't the solution to this issue.

**Comment by mariot7** [comment]
I'm closing this as I'm no longer supporting 1.12.2 versions of the mod.
