### ISSUE TITLE
Ore Dictionary Recipes

### ISSUE THREAD

**Issue by Mohron** [mariot7/XL-Food-Mod#2]
Version: XL Food Mod-1.10.2-0.3.0

Would you consider adding your salt (a semi-common mod item even to non-food mods) to the OreDictionary (itemSalt/dustSalt) and adjust the recipes that use salt to require the OreDictionary salt instead of specifically your salt? This will allow for a much more fluid experience in mod packs especially if you add more uses for your salt over time.

**Comment by mariot7** [comment]
Version 0.4.0 was just released and adds salt to the OreDictionary! Also, thank you for contributing to this project!
