### ISSUE TITLE
Tomato sauce compat with trivection chamber

### ISSUE THREAD

**Issue by SubjectHawk66** [mariot7/XL-Food-Mod#21]
**Describe your feature**

**Reasons why it should be considered**

**Additional context**

**Comment by SubjectHawk66** [comment]
Ok so I know it's dumb but the tomatos smelting into tomato sauce doesn't double in the trivection chamber which is what I would assume is a mistake possible on this mods end but idk how the thing works so I'm suggesting it here because that's what the lead dev for All the Mods suggested. It should be in this because you can get double corn but not double tomato sauce and what kind of world is that where you can't get more tomato sauce, am I right?

**Comment by mariot7** [comment]
It doesn't work because Tomato Sauce is not considered a food item but just a regular one and I don't see much point in changing that.

**Comment by SubjectHawk66** [comment]
Alright I’ll just farm more tomatoes I suppose.
