### ISSUE TITLE
Plants spawn in flat worlds with just grass

### ISSUE THREAD

**Issue by aaronhowser1** [mariot7/XL-Food-Mod#22]
**Describe the bug**
When you spawn a flat world with Grass, only Grass Blocks should spawn. Vanilla tall grass doesn't spawn, but XL Food Mod plants like Vanilla and the special Grass do.

**To Reproduce**
Spawn a flat world with just Grass

**Expected behavior**
It should only have Grass and structures

**Screenshots**
![image](https://user-images.githubusercontent.com/15698722/60628508-527cd700-9db7-11e9-8dae-3a9e02817c65.png)

**Environment**
 - Minecraft Version: 1.12
 - XL Food Mod Version: XL-Food-Mod-1.12.2-1.9.1
 - Forge Version: 14.23.5.2836

**Comment by mariot7** [comment]
If I understand correctly you're saying that only grass blocks should spawn without both the vanilla grass and XL Food Mod's vanilla flowers and grass. Am I right?

**Comment by aaronhowser1** [comment]
Exactly

**Comment by mariot7** [comment]
Gotcha. I'll see what I can do.

**Comment by mariot7** [comment]
This has been fixed in versions for 1.14.4 and 1.15.1.
