### ISSUE TITLE
[1.14.4] Plant drops in loot table

### ISSUE THREAD

**Issue by kwpugh** [mariot7/XL-Food-Mod#27]
**Describe your feature**
With the move to 1.13/1.14, Mojang moved block drops to loot tables, rather than having them hard coded in classes.  Do you have plans to do that?

**Reasons why it should be considered**
Your crops have a nice right-click harvest feature and spawn drop in each block class, but it makes it rather difficult to have auto-harvest devices (unless you know a way to accomplish that).
I have area harvest items in my mod that check for max age, destroy the block, and sets its default state at age 0, relying on the block's defined loot table drop to spawn.   Yours don't do that due to no loot drops defined.   I hope this makes sense.

Thank you for considering.

**Additional context**

**Comment by mariot7** [comment]
You bring up a fair point. I'll definitely consider it!

**Comment by mariot7** [comment]
Added in v2.1.0.
