### ISSUE TITLE
In 1.14.4 recipes that use buckets of milk or water don't return the bucket

### ISSUE THREAD

**Issue by Lemon-Juiced** [mariot7/XL-Food-Mod#30]
If you were to craft either dough or cheese the buckets aren't returned to you, I mean dedicating 18 pieces of iron to 4 cheese is pretty pricy.

I just wanted to make some grilled cheese and now I'm dirt poor.

**Environment**
 - Minecraft Version: 1.14.4
 - XL Food Mod Version: XL-Food-Mod-1.14.4-2.0.3
 - Forge Version: 28.0.40

**Comment by mariot7** [comment]
Weird... I can't reproduce this.

**Comment by Lemon-Juiced** [comment]
I just realized I was using the Crafting Station mod by tfarecnim, and buckets disappeared from that, I don't remember what version of that mod though, so it might be on that mods behalf.
