### ISSUE TITLE
[1.14.4] Can you add Forge tag for fruit?

### ISSUE THREAD

**Issue by kwpugh** [mariot7/XL-Food-Mod#31]
Hi,

I was wondering if you would consider adding a forge tag for the fruits in your mod? This would help for cross mod compatibility.

I make a mod called Veggie Way that uses fruits to create fructose powder for making superfood powder.

Here is an example from Simple Farming: https://github.com/enemeez/simplefarming/tree/master/src/main/resources

Thank you for considering.

Regards.

**Comment by mariot7** [comment]
Sure. I'm going to add vegetables to the tag system as well.

**Comment by mariot7** [comment]
Added in v2.1.1.

**Comment by kwpugh** [comment]
Thank you.
