### ISSUE TITLE
Compatibility with Culinary Construct

### ISSUE THREAD

**Issue by MitztheKat** [mariot7/XL-Food-Mod#33]
Please speak with him. i will ask him about compatibility. 
https://www.curseforge.com/minecraft/mc-mods/culinary-construct
current compatible mod is - to be honest - too confusing. and uses too much repetition of useless ingredients
and the other is pam's but currently i am trying to make a fun pack that doesn't use pam's or tinkers.
lemme make some damn tasty sammiches!

**Comment by mariot7** [comment]
You don't have to ask. It's pretty easy to add my own items for it so I'll make it compatible myself.

**Comment by MitztheKat** [comment]
i'll be waiting. i have a modpack to dev. currently making some petty cookie-dough-vanilla pack. it's the crossroads between modded addicts and people who've never modded before (my brother).
