### ISSUE TITLE
Crops not generating in server, but generates offline

### ISSUE THREAD

**Issue by DimebagDarrell1990** [mariot7/XL-Food-Mod#36]
Im new to github so sorry if that bothers you.
I'm having an issue where the mod works offline, but the crops do not generate on the server I created. If I tried to go into creative and spawn in vanilla plants or grass from the mod, it simply disappear immediately.

**Comment by mariot7** [comment]
Um... you closed this issue. Does that mean the problem is no longer persistent?

**Comment by DimebagDarrell1990** [comment]
> Um... you closed this issue. Does that mean the problem is no longer persistent?

Yeah sorry I closed it because it was my fault and I found out what it was. It wasn't the mods issue. I closed it fast cause I didn't want to look stupid, sorry
