### ISSUE TITLE
XL Foods is crashing with Security Craft and MrCrayfish's Furniture Mod

### ISSUE THREAD

**Issue by MrEAZL** [mariot7/XL-Food-Mod#37]
As title says but I dont know if its compitable with optifine and aternos loads successfully but my game freezes in "loading terrain" screen and its really annoying Im scared of if we cant play (with my friends) that would suck

**Comment by mariot7** [comment]
Give me more info. Which version of said mods are you using? Which Minecraft and Forge versions are you using?

**Comment by MrEAZL** [comment]
nvm I fixed the problem, the problem was jei, sorry about that
