### ISSUE TITLE
Onions don't drop when harvested

### ISSUE THREAD

**Issue by StefanH-AT** [mariot7/XL-Food-Mod#39]
**Describe the bug**
Onion crops never drop anything unless being harvested with a fortune tool, which gives a ~50% chance to get one onion. The loottable is the cause of the issue here, since it does not include any drops for it.

**To Reproduce**
1. Go to crop
2. Harvest crop
3. Nothing drops

**Expected behavior**
Crop should drop the produce

**Additional context**  
I fixed this on my server with a custom datapack that replaces the block's loottable.

**Environment**
 - Minecraft Version: 1.14.4
 - XL Food Mod Version: 2.1.1
 - Forge Version: does not matter here

**Comment by mariot7** [comment]
Thank you for reporting this!

**Comment by mariot7** [comment]
Fixed in v2.2.0.
