### ISSUE TITLE
Blockstate location exception?

### ISSUE THREAD

**Issue by DatrixTHLK** [mariot7/XL-Food-Mod#4]
Hi @mariot7 ,

I'm receiving this error from my FML log for reasons I'm unsure of.

https://gist.github.com/DatrixTHLK/732365a23e0815aff4bcad49bf280955
Lines 1530-1623, 1696-1723, 1770-1816

Minecraft 1.10.2
Forge 12.18.2.2022
XL Food Mod: 0.5.0

**Comment by mariot7** [comment]
I'll fix this in the next update which will come out ASAP. Thank you for letting me know about this!

**Comment by DatrixTHLK** [comment]
Your welcome. =)

**Comment by DatrixTHLK** [comment]
You're welcome! :) Thanks for the response.

**Comment by mariot7** [comment]
Version 0.6.0 has now been released! I'm really sorry for not updating the mod in such a long time. Thanks for reporting this issue!

**Comment by DatrixTHLK** [comment]
No worries. I've taken a break from minecraft because I got bored again. I'll be back at it soon though. Thanks for fixing the issue. I appreciate it.
