### ISSUE TITLE
Suggestion - A book with crafting recipes? 

### ISSUE THREAD

**Issue by admiralamott1** [mariot7/XL-Food-Mod#42]
There's a ton of new food for this mod and it gets kinda annoying having to keep tabbing to my browser and finding the mod page to find a recipe, I think it would be a lot better if there was a recipe book you could just read instead?

**Comment by mariot7** [comment]
Use Just Enough Items mod instead

**Comment by admiralamott1** [comment]
Didnt know that existed, thanks!
