### ISSUE TITLE
Integration with Immersive Engineering

### ISSUE THREAD

**Issue by MeanestLarva** [mariot7/XL-Food-Mod#43]
**Describe your feature**
I'd like to be able to grow XL Food Mod crops in Immersive Engineering's Garden Cloches.

**Reasons why it should be considered**
More parity between how vanilla crops and XL Food Mod crops work.

Thanks for your consideration.

**Comment by mariot7** [comment]
Somebody already made it compatible and opened a pull request in BluSunrize/ImmersiveEngineering#3449. Right now it's a waiting game for when the author's going to add it.

**Comment by mariot7** [comment]
The pull request was merged and it should be compatible with XL Food's crops now.
