### ISSUE TITLE
Crops have black boxes around them

### ISSUE THREAD

**Issue by Redrose716** [mariot7/XL-Food-Mod#44]
![XL Foods Mod](https://user-images.githubusercontent.com/59212604/71426900-c0230500-266e-11ea-94c7-24a3bd9a254a.jpg)

**Comment by mariot7** [comment]
Which version of Forge are you using?

**Comment by Redrose716** [comment]
30.0.15

**Comment by mariot7** [comment]
I can't reproduce this, unfortunately. Try updating Forge to 30.0.16. If the issue persists give me the list of mods you're using.
