### ISSUE TITLE
Cappuccino recipe just outputs coffee

### ISSUE THREAD

**Issue by katubug** [mariot7/XL-Food-Mod#49]
**Describe the bug**
Hi there! I discovered today when I tried to make a cappuccino that the recipe outputs a regular coffee.

**Screenshots**
![2020-01-19_15 44 55](https://user-images.githubusercontent.com/20935286/72689055-e3589d00-3ad2-11ea-8745-df26bf60c853.png)
Note that the recipe ID specifies that it is meant to be cappuccino. I have never said the word "cappuccino" so much in my life, it doesn't even look like a real word anymore. xD 

**Additional context**
I am using this in a modpack environment, and I have not tested xlfoodmod on its own. However, I do not think that the recipe is being altered by another mod. I can do further testing if you cannot replicate.

**Environment**
 - Minecraft Version: 1.12.2
 - XL Food Mod Version: 1.9.2
 - Forge Version: 2847

**Comment by mariot7** [comment]
Hello,

I'll have to disappoint and say that I'm no longer updating the mod for 1.12.2, only for 1.14.4 and 1.15.1.
