### ISSUE TITLE
Latest Version for 1.15.2 Crashes Server

### ISSUE THREAD

**Issue by Camawama** [mariot7/XL-Food-Mod#51]
**Describe the bug**
The server will not start, crashes with a crash report

**To Reproduce**
Use same mods in my Modpack and attempt to start the server with XL Food Mod

**Expected behavior**
I expected the server to start and work

**Additional context**
I provided a zip file with the crash report, logs, and a list of mods used

**Environment**
 - Minecraft Version: 1.15.2
 - XL Food Mod Version: 2.2.2
 - Forge Version: 31.0.14
[XL Food Mod.zip](https://github.com/mariot7/XL-Food-Mod/files/4137839/XL.Food.Mod.zip)

**Comment by mariot7** [comment]
I can't reproduce this. I installed (almost) all of the mods you were using and the server starts normally, without crashes.

I'd advise you to update all your mods to the latest version if you haven't already and, if that doesn't work, upload all of your server files to a site like Dropbox, Google Disc or somewhere similar so I can find out what's causing this.

**Comment by Camawama** [comment]
I don't know what changed but the server works perfectly now. I have been adding and removing Mods so there might've been some conflict but I guess I won't know now. One thing though, I got this mod that adds stuff to the nether (More Mobs, More Blocks, etc) and the plant in your mod keeps growing on the Nether Dirt lol

**Comment by mariot7** [comment]
I'm aware of that. I'll see what I can do about it.
