### ISSUE TITLE
[1.15.2] Issue with XL grass blocking/replacing vanilla flowers

### ISSUE THREAD

**Issue by kwpugh** [mariot7/XL-Food-Mod#61]
**Describe the bug**
Hi, I'm the author of Gobber and I have a growth ring in my mod.  Among other things, it will tick grass blocks to grow their natural "crops" (e.g. tall grass and biome flowers).   However, with XL Food installed, no flowers and all one gets is tall grass and XL Food grass that drop seeds.  In looking in your OreGenerator class, I believe you are overriding the vanilla flower generation, but I am not completely sure.

**To Reproduce**
Load up a world with Gobber mod or standalone Ring of Growth mod, hold the Ring of the Farmer or Ring of Growth in your main hand and wait a sec, tall grass and flowers abound.
Add XL Food into the mix, repeat the process and no flowers, just lots of XL Grass
NOTE: This behavior also occurs with vanilla bonemeal and XL Food, so your method is also blocking players from growing flowers on grass blocks.

**Expected behavior**
Natural vanilla flower growth should occur.   The method I use is based on the way vanilla Bonemeal grows grass and flowers.   

**Screenshots**
N/A

**Additional context**
N/A

**Environment**
 - Minecraft Version: 1.15.2
 - XL Food Mod Version: 
 - Forge Version:

**Comment by kwpugh** [comment]
Additional reference:

My items is calling the GrassBlock's grow() method.

if(block instanceof GrassBlock && player.isShiftKeyDown())
{
    if (player.ticksExisted % 120 == 0)
    {
          ((GrassBlock) block).grow((ServerWorld) world, world.rand, targetPos, blockstate);	
     }
}

**Comment by mariot7** [comment]
I can't reproduce this by following your instructions.

I've installed Gobber, created a new world, grabbed Ring of the Farmer, shift-right clicked on grass; flowers and tall grass spawned around. I've then installed XL Food Mod and repeated the process and got the same results - flowers and tall grass spawned around the grass I right-clicked on.

**Comment by kwpugh** [comment]
Ok, I will look further at other possible causes
