### ISSUE TITLE
Compatibility issue with random things

### ISSUE THREAD

**Issue by Mofo50C** [mariot7/XL-Food-Mod#67]
**Describe the bug**
Seeds pop off when planted on tilled fertilised dirt from random things.

**To Reproduce**
1. get fertilised dirt
2. till it
3. plant a seed from xl food

**Expected behavior**
it shouldnt pop off...

**Environment**
 - Minecraft Version: 1.12.2
 - XL Food Mod Version: 1.9.2 latest 1.12
 - Forge Version: 14.23.5.2854

**Comment by mariot7** [comment]
I'm no longer supporting the 1.12 version, unfortunately.
