### ISSUE TITLE
[1.11.2] Cascading worldgen lag!

### ISSUE THREAD

**Issue by Tokeli** [mariot7/XL-Food-Mod#7]
On forge 13.20.1.2386, there's a surprising, and sometimes painful, worldgen cascade, and it looks like it's from the flower generation.

![image](https://user-images.githubusercontent.com/6316563/29492573-f11ad68e-854d-11e7-8c1e-b8b8cdbb6ace.png)

Are your flowers generating too close to the chunk boundary?

**Comment by mariot7** [comment]
Thanks for letting me know about this, I'll attempt to fix this ASAP, maybe even today.

**Comment by mariot7** [comment]
I've now released version 1.0.1 that fixes this issue. Thanks for reporting this!

**Comment by Tokeli** [comment]
I love this mod, so, great to see that fixed! :D
