### ISSUE TITLE
Crash when starting a new world

### ISSUE THREAD

**Issue by davqvist** [mariot7/XL-Food-Mod#9]
MC 1.12.1
Forge 2469
XL Food Mod 1.0.1

https://pastebin.com/Y296ufra

As you can see, it has some incompability with Biomes O Plenty. I can reproduce it regularly, but it happens only about every second time. Also, I set everything in the config to false to prevent any world gen basically, but it still happens.

**Comment by mariot7** [comment]
This has already been mentioned in #8. We'll see if it still happens after the next update

**Comment by davqvist** [comment]
Is there an ETA of the next update? Or did it happen and I can't find it? No pressure, just wondering.

**Comment by mariot7** [comment]
Major updates are released once a month, so should be out soon*.

**Comment by davqvist** [comment]
Thanks for the quick answer.

**Comment by mariot7** [comment]
I've now released a new version of the mod that fixes this issue. Thanks for the help!
